### PR TITLE
Fixing duplicate rows issue in XmlInputFormat #171

### PR DESCRIPTION
**Pull request by lokm01**
Fix for issue #171

### CODE REVIEW

**Comment by lokm01** [comment]
@HyukjinKwon

**Comment by HyukjinKwon** [comment]
Hi @lokm01 , I didn't take a look so closely but I resembled [LineRecordReader.java#L94-L134](https://github.com/apache/hadoop/blob/branch-2.2.0/hadoop-mapreduce-project/hadoop-mapreduce-client/hadoop-mapreduce-client-core/src/main/java/org/apache/hadoop/mapred/LineRecordReader.java#L94-L134) in Hadoop 2.2.0. However, in a recent version, I noticed it was changed to [LineRecordReader.java#L97-L146](https://github.com/apache/hadoop/blob/branch-3.0.0-alpha1/hadoop-mapreduce-project/hadoop-mapreduce-client/hadoop-mapreduce-client-core/src/main/java/org/apache/hadoop/mapred/LineRecordReader.java#L97-L146) in Hadoop 3.0.0. And assuming from the related commit, https://github.com/apache/hadoop/commit/9227dfc25f373a99cb66ad7d6bacef8dcf336f77, it seems the issue is similar?

Could you maybe check if the problem is the same and resemble the way if so? I would like to track down the changes there rather than duplicating the efforts.

**Comment by HyukjinKwon** [comment]
BTW, maybe it seems you have something wrong with updating your PR. I will leave some notes for this just in case. Maybe you could do as below:

```
git remote add upstream https://github.com/databricks/spark-xml.git
git fetch upstream
git checkout issue-171
git merge upstream/master
git push origin issue-171
```

There are several ways to update your PR such as rebasing or squashing. I found this reference is good, https://github.com/druid-io/druid/blob/master/CONTRIBUTING.md

**Comment by HyukjinKwon** [comment]
ping @lokm01 If you don't have some time, I will do this maybe within next few weeks.

**Comment by lokm01** [comment]
Will have a look during the week.

**Comment by lokm01** [comment]
I am closing this PR. #161 seems to fix this particular issue, though I found another problem with compressed files which appeared with #161 need to investigate this further.

**Pull request closed without merging**
