### PR TITLE
Added documentation entry to warn against self closing row tags

### PR DESCRIPTION
**Pull request by trheming**

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
Cool. It is always good to document the limitation. Thanks. Could you maybe copy and paste it to `rowTag` in the writing options below?

**Comment by trheming** [comment]
Not positive, but my understanding is that the writer will never be able to encounter this condition when saving out a dataframe? Things would default to `<rowTag> </rowTag>`. Is this correct?

**Comment by HyukjinKwon** [comment]
Oh, yes. I was thinking when someone might want to write out with self-closing tags by kind of an option. Yea, but it sounds less common. LGTM. Let me merge this tomorrow (due to network problem).

**Comment by HyukjinKwon** [comment]
Thank you @trheming, merging to master.

**Pull request closed without merging**
