### PR TITLE
Support for PERMISSIVE/DROPMALFORMED mode and corrupt record option.

### PR DESCRIPTION
**Pull request by HyukjinKwon**
https://github.com/databricks/spark-xml/issues/105

Currently, this library does not support `PERMISSIVE` parse mode. Similar with JSON data source, this also can be done in the same way with `_corrupt_record`.

This PR adds the support for `PERMISSIVE` mode and make this behaviour consistent with the other data sources supporting parse modes (JSON and CSV data sources.)

Also, this PR adds the support for `_corrupt_record`.

This PR is similar with https://github.com/apache/spark/pull/11756 and https://github.com/apache/spark/pull/11881.

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
@cloud-fan Do you mind if I ask a quick look for this please? I rememeber JSON parse modes were reviewed by you.

**Comment by cloud-fan** [comment]
Haven't we absorbed it into Spark already?

**Comment by HyukjinKwon** [comment]
@cloud-fan Ah, no CSV was ported into Spark but XML one has not been. I have been managine this and confused who I should cc.

**Comment by cloud-fan** [comment]
cc @rxin

**Comment by HyukjinKwon** [comment]
Sorry for cc here and there @cloud-fan. Could you please give a quick look please?

**Comment by HyukjinKwon** [comment]
Maybe I will merge this after double-checking this by myself if you have time to review this PR (but will wait more just in case) - @cloud-fan

**Comment by HyukjinKwon** [comment]
I am going to merge this as soon as the tests pass.

**Pull request closed without merging**
