### PR TITLE
Initial pass at supports 'paths' data source option with multiple file paths

### PR DESCRIPTION
**Pull request by srowen**
(Pull request for testing - TBD)

### CODE REVIEW

**Comment by zsxwing** [comment]
Is it possible to write a test using `spark.read.format("xml").load(paths: _*)` to verify the change?

**Comment by srowen** [comment]
@zsxwing heh yeah it doesn't work. Looking more closely, it seems like "paths" is a DSv2 thing, and only "path" is set for legacy V1 sources (like this). I can try a hack but really this seems tied up with V2 support I guess, and I don't know how to do that

**Comment by zsxwing** [comment]
After checking the code, I also realized that `load(paths)` in DSv1 only works for `FileFormat` which is the internal interface for built-in file formats 😢 

Thanks for quickly working on this! I think we have to give up this as moving DSv2 is unrealistic.

**Comment by srowen** [comment]
OK canning this for now. Thanks for checking!

**Pull request closed without merging**
