### PR TITLE
Dummy change to test CI/CD. Not to be merged.

### PR DESCRIPTION
**Pull request by srowen**

### CODE REVIEW

**Comment by srowen** [comment]
@HyukjinKwon please don't spend any significant time on this, but I thought you might know - I recently committed changes to this repo to use Github actions to test. They don't seem to be working. Do you see any issue with how https://github.com/databricks/spark-xml/blob/master/.github/workflows/test_spark_3_java_11.yml is declared, off the top of your head?

**Comment by HyukjinKwon** [comment]
oh, IIRC `$default-branch` can only be used when running the shell (instead of defining workflow itself). let me make a quick try.

**Comment by HyukjinKwon** [comment]
oh no, that's updated at https://github.blog/changelog/2020-07-22-github-actions-better-support-for-alternative-default-branch-names/ so we can use `$default-branch`, hm.

**Comment by HyukjinKwon** [comment]
Made a PR at https://github.com/databricks/spark-xml/pull/545. let me close this one :-).

**Comment by srowen** [comment]
Just reopening to test --

**Pull request closed without merging**
